### Listener at same Thread - Transaction Commit
GET http://localhost:8080/same-thread/transaction-commit

### Listener at same Thread - Transaction Rollback
GET http://localhost:8080/same-thread/transaction-rollback

### Listener at same Thread - Listener Error and Slow
GET http://localhost:8080/same-thread/listener-error

### Listener at different Thread - Transaction Commit
GET http://localhost:8080/other-thread/transaction-commit

### Listener at different Thread - Transaction Rollback
GET http://localhost:8080/other-thread/transaction-rollback